function [MeanSpectra, v_TimeAxis,v_FreqAxis,...
    DeltaPower, ThetaPower, AlphaPower,SpindlePower,BetaPower] = ...
    f_Multitaper_ROI(Data,file,scout,s_baselineStart,s_baselineEnd,...
    s_TimeBeforeCero,ChanVsSource)

[MeanSpectra,v_TimeAxis, v_FreqAxis] = ....
    f_MultitaperAnalysis(scout,Data,file,s_baselineStart,...
    s_baselineEnd,s_TimeBeforeCero,ChanVsSource);

[DeltaPower,...
    ThetaPower,...
    AlphaPower,...
    SpindlePower,...
    BetaPower] = ...
    f_FreqCalc(MeanSpectra,v_FreqAxis);
end

